// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"alipaycloudrun-demo-for-go/api"
	"alipaycloudrun-demo-for-go/api/handlers"
	"alipaycloudrun-demo-for-go/app"
	"alipaycloudrun-demo-for-go/internal/service"
	"alipaycloudrun-demo-for-go/repo"
)

// Injectors from wire.go:

func InitServer() *app.Server {
	engine := app.NewGinEngine()
	db := app.InitDB()
	iRecordRepo := repo.NewMysqlArticleRepository(db)
	iDbService := service.NewDbService(iRecordRepo)
	recordHandler := handlers.NewRecordHandler(iDbService)
	iHttpService := service.NewHttpService()
	httpHandler := handlers.NewHttpHandler(iHttpService)
	client := app.InitRedis()
	iRedisService := service.NewRedisService(client)
	redisHandler := handlers.NewRedisHandler(iRedisService)
	router := api.NewRouter(recordHandler, httpHandler, redisHandler)
	server := app.NewServer(engine, router)
	return server
}
